name: Push Event Workflow

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Add your build and test steps here
    - name: Build and Test
      run: |
        # Your build and test commands go here
        echo "Building and testing..."
